### ISSUE TITLE
discussing "install"

### ISSUE THREAD

**Issue by iurisegtovich** [craabreu/emdee#3]
i believe we have two macro options

1) touch some global system configs which require sudo:
e.g. current approach:
sudo make install
	cp $(LIBDIR)/libemdee.* /usr/local/lib/
	cp $(INCDIR)/emdee.* /usr/local/include/
	ldconfig

2) keep the files locally and instruct the linker of tests and jobs on how to find them at compile time and at run time
  2a) in fortran and c, to find them at compile time we can use -I$(libdir) as a linker option
  2b) to make the executable able to find them at run time we can use something like
    2b_i)        $(LINK) -Wl,-rpath,'$$ORIGIN/../../lib1/so'
    i will implement it specifically for our makefile soon

    2b_ii) compile using  -static

    2b_iii) in julia, as julia is not compiled/linked we will have to deal with its package management system

      2a_iii_1 ship lib to /home/**user**/.julia/**version**/EmDee/lib/libemdee.so
      Libdl.dlopen("/home/**user**/.julia/**version**/EmDee/lib/libemdee.so")
      ship wrappers in EmDee.jl so any script.jl can run "using EmDee"
      ship it to to ~/.julia/v0.4/EmDee/src

      2a_iii_2 include in julia source:  
      Libdl.dlopen("**EmDee-source-folder**/lib/libemdee.so")

      ? 
        Julia include path for USING MODULE
          abrir pasta dos packages:
            ~/.julia
          colar EmDee.jl em ~/.julia/v0.4/EmDee/src
      ?
         Julia load shared library EmDee.so
           http://docs.julialang.org/en/release-0.4/manual/modules/
           http://docs.julialang.org/en/release-0.4/stdlib/libdl/

      !
         I'm currently trying and will submmit an approach that combines Libdl.dlopen, Libdl.dlsym, and a home made macro from http://docs.julialang.org/en/release-0.5/manual/calling-c-and-fortran-code/

this decision is relevant for both the EmDee library as for the gfortran libraries, both can be linked either statically or dinamically

Obs: is there a reason to make libgfortran statically linked or should i find the right options to make it dinamically linked?

**Comment by iurisegtovich** [comment]
please see my proposal on how to get rid of "sudo make install" on my latest commit to my master branch

**Comment by craabreu** [comment]
1) Option 2 (with 2a and 2b_i) is preferable.
2) Regarding Julia, it seems more practical to make the test script (testjulia.jl) tell Julia where to look for the module (EmDee.jl) and for the shared library (libemdee.so) instead of copying any files. We don't want to get rid of the install option in Makefile. We just want that testjulia.jl finds EmDee.jl in the local path and then EmDee.jl finds the shared library also in the local path, even if outdated versions of these files exist in the system path.
3) Statically linking libgfortran is sometimes necessary (e.g. when compiling with devtoolset whose gfortran version differs from that installed in the system path). But I think it is better to let this as an option in Makefile (default = shared).

**Comment by craabreu** [comment]
@iurisegtovich, I managed to make juliatest look for the module EmDee.jl and the shared library libemdee.so in the local path, so that it will always use the most up-to-date version during the tests. Other changed features were: 1) install and uninstall goals reactivated in Makefile and added to README.md and 2) instructions to build a static library removed from Makefile (since it has never been tested). If you agree, we can mark this issue as closed.

**Comment by iurisegtovich** [comment]
Agreed
